### ISSUE TITLE
mancanza del tag opegraph og:image

### ISSUE THREAD

**Issue by mguidotto** [fevrcoding/fevrcoding.github.io#1]
hi Luca, ciao!
stai dimenticando opportunità importante per tuo lavoro di web sviluppo

`<meta property="og:image"              content="http://static01.nyt.com/images/2015/02/19/arts/international/19iht-btnumbers19A/19iht-btnumbers19A-facebookJumbo-v2.jpg" />`

**Comment by kino90** [comment]
dovrebbe bastare aggiungere il metatag `image` all'interno dell'heading dei post
ref. https://github.com/jekyll/jekyll-seo-tag 

```
image:
  twitter: /img/twitter.png
  facebook: /img/facebook.png
  height: 100
  width: 100
```
